CREATE TABLE COLLECTION(
  COLLECTION_ID     VARCHAR(50) NOT NULL,
  ENVIRONMENT_ID    VARCHAR(50),
  VERSION           VARCHAR(20),
  REMARK            VARCHAR(300),
  STATUS            INTEGER NOT NULL DEFAULT 0,
  DELETE_FLAG       INTEGER NOT NULL DEFAULT 0,
  INSERT_USER 			VARCHAR(50),
  INSERT_TIME 			TIMESTAMP DEFAULT,
  UPDATE_USER    		VARCHAR(50),
  UPDATE_TIME 			TIMESTAMP DEFAULT,
  PRIMARY KEY (COLLECTION_ID)
);
