CREATE TABLE TRAINING_QUERY(
  QUERY_ID      INTEGER NOT NULL,
  QUERY         VARCHAR(32500) NOT NULL,
  DELETE_FLAG   INTEGER NOT NULL DEFAULT 0,
  INSERT_USER 	VARCHAR(50),
  INSERT_TIME 	TIMESTAMP DEFAULT,
  UPDATE_USER   VARCHAR(50),
  UPDATE_TIME 	TIMESTAMP DEFAULT,
  PRIMARY KEY (QUERY_ID)
) ORGANIZE BY ROW;
