CREATE TABLE TRAINING_RELEVANCE(
  QUERY_ID      INTEGER NOT NULL,
  DATA_ID       INTEGER NOT NULL,
  RELEVANCE     INTEGER NOT NULL,
  INSERT_USER 	VARCHAR(50),
  INSERT_TIME 	TIMESTAMP DEFAULT,
  UPDATE_USER   VARCHAR(50),
  UPDATE_TIME 	TIMESTAMP DEFAULT,
  PRIMARY KEY (QUERY_ID,DATA_ID),
  FOREIGN KEY (QUERY_ID) REFERENCES TRAINING_QUERY
) ORGANIZE BY ROW;
