CREATE TABLE USER_MASTER(
  USER_ID       VARCHAR(50) NOT NULL,
  USER_PASSWORD VARCHAR(64),
  ADMIN_FLAG    INT NOT NULL DEFAULT 0,
  USER_NAME     VARCHAR(300),
  INSERT_USER   VARCHAR(50),
  INSERT_TIME   TIMESTAMP DEFAULT,
  UPDATE_USER   VARCHAR(50),
  UPDATE_TIME   TIMESTAMP DEFAULT,
  PRIMARY KEY (USER_ID)
);
