CREATE TABLE USER_FEEDBACK(
  FEEDBACK_ID   INT NOT NULL
    GENERATED ALWAYS AS IDENTITY
      (START WITH 1,
       INCREMENT BY 1,
       MINVALUE 1,
       NO MAXVALUE,
       NO CYCLE,
       NO CACHE),
  QUESTION_ID   VARCHAR(32) NOT NULL,
  DATA_ID       INTEGER,
  COPE_FLAG     INTEGER NOT NULL DEFAULT 0,
  INSERT_USER   VARCHAR(50),
  INSERT_TIME   TIMESTAMP DEFAULT,
  UPDATE_USER   VARCHAR(50),
  UPDATE_TIME   TIMESTAMP DEFAULT,
  PRIMARY KEY (FEEDBACK_ID)
);
